name: FocalTestArmv7
on: workflow_dispatch

jobs:

  BuildFocalarmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh focal arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh focal arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FocalServerPackage
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

