name: BuildServerPackages
on: workflow_dispatch

jobs:
  BuildBusterArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh buster arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh buster arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BusterServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestBusterArm64:
    needs: BuildBusterArm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: BusterServerPackageArm64
          path: githubActionsBuild/in

      - name: TestingPackageArm64
        run: |
           ./githubActionsBuild/createTestingImage.sh buster arm64
           ./githubActionsBuild/startServerPackageTest.sh buster arm64

  BuildBusterArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh buster arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh buster arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BusterServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestBusterArmv7:
    needs: BuildBusterArmv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: BusterServerPackageArmv7
          path: githubActionsBuild/in

      - name: TestingPackageArmv7
        run: |
           ./githubActionsBuild/createTestingImage.sh buster arm/v7
           ./githubActionsBuild/startServerPackageTest.sh buster arm/v7

  BuildBullseyeArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh bullseye arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bullseye arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BullseyeServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestBullseyeArm64:
    needs: BuildBullseyeArm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: BullseyeServerPackageArm64
          path: githubActionsBuild/in

      - name: TestingPackageArm64
        run: |
           ./githubActionsBuild/createTestingImage.sh bullseye arm64
           ./githubActionsBuild/startServerPackageTest.sh bullseye arm64

  BuildBullseyeArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh bullseye arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bullseye arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BullseyeServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestBullseyeArmv7:
    needs: BuildBullseyeArmv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: BullseyeServerPackageArmv7
          path: githubActionsBuild/in

      - name: TestingPackageArmv7
        run: |
           ./githubActionsBuild/createTestingImage.sh bullseye arm/v7
           ./githubActionsBuild/startServerPackageTest.sh bullseye arm/v7

  BuildBookwormArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh bookworm arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bookworm arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BookwormServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestBookwormArm64:
    needs: BuildBookwormArm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: BookwormServerPackageArm64
          path: githubActionsBuild/in

      - name: TestingPackageArm64
        run: |
           ./githubActionsBuild/createTestingImage.sh bookworm arm64
           ./githubActionsBuild/startServerPackageTest.sh bookworm arm64

  BuildBookwormArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh bookworm arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bookworm arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BookwormServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestBookwormArmv7:
    needs: BuildBookwormArmv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: BookwormServerPackageArmv7
          path: githubActionsBuild/in

      - name: TestingPackageArmv7
        run: |
           ./githubActionsBuild/createTestingImage.sh bookworm arm/v7
           ./githubActionsBuild/startServerPackageTest.sh bookworm arm/v7

  BuildFocalArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh focal arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh focal arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FocalServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestFocalArm64:
    needs: BuildFocalArm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: FocalServerPackageArm64
          path: githubActionsBuild/in

      - name: TestingPackageArm64
        run: |
           ./githubActionsBuild/createTestingImage.sh focal arm64
           ./githubActionsBuild/startServerPackageTest.sh focal arm64

  BuildFocalArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh focal arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh focal arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FocalServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestFocalArmv7:
    needs: BuildFocalArmv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: FocalServerPackageArmv7
          path: githubActionsBuild/in

      - name: TestingPackageArmv7
        run: |
           ./githubActionsBuild/createTestingImage.sh focal arm/v7
           ./githubActionsBuild/startServerPackageTest.sh focal arm/v7

  BuildJammyArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh jammy arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh jammy arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JammyServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestJammyArm64:
    needs: BuildJammyArm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: JammyServerPackageArm64
          path: githubActionsBuild/in

      - name: TestingPackageArm64
        run: |
           ./githubActionsBuild/createTestingImage.sh jammy arm64
           ./githubActionsBuild/startServerPackageTest.sh jammy arm64

  BuildJammyArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh jammy arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh jammy arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JammyServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  TestJammyArmv7:
    needs: BuildJammyArmv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - uses: actions/download-artifact@v3
        with:
          name: JammyServerPackageArmv7
          path: githubActionsBuild/in

      - name: TestingPackageArmv7
        run: |
           ./githubActionsBuild/createTestingImage.sh jammy arm/v7
           ./githubActionsBuild/startServerPackageTest.sh jammy arm/v7
