name: BuildServerPackages
on: workflow_dispatch

jobs:
  BuildBusterArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh buster arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh buster arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BusterServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildBusterArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh buster arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh buster arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BusterServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildBullseyeArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh bullseye arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bullseye arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BullseyeServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildBullseyeArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh bullseye arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bullseye arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BullseyeServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildBookwormArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh bookworm arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bookworm arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BookwormServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildBookwormArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh bookworm arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh bookworm arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BookwormServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildFocalArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh focal arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh focal arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FocalServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildFocalArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh focal arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh focal arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FocalServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildJammyArm64:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArm64
        run: |
           ./githubActionsBuild/createBuildImage.sh jammy arm64 go1.20.4.linux-arm64.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh jammy arm64

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JammyServerPackageArm64
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

  BuildJammyArmv7:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: PrepareHost
        run: |
           ./githubActionsBuild/prepareHost.sh

      - name: BuildPackageArmv7
        run: |
           ./githubActionsBuild/createBuildImage.sh jammy arm/v7 go1.20.4.linux-armv6l.tar.gz
           VERSION=10.0.1 ./githubActionsBuild/buildServerPackage.sh jammy arm/v7

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JammyServerPackageArmv7
          path: |
            githubActionsBuild/out/**/built-seafile-server-pkgs/*.tar.gz

